### ISSUE TITLE
Hidden SSID

### ISSUE THREAD

**Issue by OneKelPeta** [RPi-Distro/raspi-config#106]
Can't connect to hidden SSID.
Need to configure wpa_supplicant.conf myself to get it working.

**Comment by XECDesign** [comment]
IIRC, it was decided that there's no reason to support hidden SSIDs in raspi-config. It's a question many users won't understand and I'm not aware of any compelling reason to ask them. Editing by wpa_supplicant.conf is the recommended approach.
