### ISSUE TITLE
Boot Options Desktop / CLI Reset root password

### ISSUE THREAD

**Issue by h0m3** [RPi-Distro/raspi-config#107]
When you choose an option in Boot Options > Desktop / CLI menu the script resets the root password without telling the user.

When I rebooted the system i was locked out because the only user that was present in the system was root, I needed to unplug the PI from the wall since there's no way to reset or shutdown without login and it can cause data corruption in the drive and then start the pi in single user mode to setup a new root password and keep using my system.

It's a pretty specific situation because normally you wouldn't run your system as root but since i was configuring my system and i didn't add any other user into the system i was locked out. I do delete the 'pi' user at first boot for security reasons and then create my own user.

I think this issue can be easly fixed by checking if the 'pi' user still exists or by showing a warning to the user telling that the root password is being reset.

**Comment by XECDesign** [comment]
> When you choose an option in Boot Options > Desktop / CLI menu the script resets the root password without telling the user.

I don't see that in the script. Do you have a line number?

There has been an update to address issues that happen when you run raspi-config directly as root rather than through sudo and I suspect that will take care of whatever issue you had once that version of raspi-config is released.
