### ISSUE TITLE
Per official style guide, WiFi, Wi-Fi should not be used to refer to wireless LAN

### ISSUE THREAD

**Issue by andrum99** [RPi-Distro/raspi-config#114]
Per https://github.com/raspberrypilearning/style-guide/blob/master/style-guide.md, which is the official style guide for Raspberry Pi Trading and the Raspberry Pi Foundation, the term WiFi, or Wi-Fi, should only be used where it is certain that the device in question has been certified by the Wi-Fi Alliance, and has licenced the trademark. (Or at least, that is what it implies when it refers to a device being "licenced").

Since raspi-config cannot know for certain which wireless devices a user might have connected, it is not possible to know whether that device is licenced, and therefore whether the style 'WiFi' or 'Wi-Fi' can legitimately be used.

The fix is to refer to WiFi as "wireless LAN" or "wireless networking" in all places within raspi-config. The style guide suggests "wireless LAN".

**Comment by XECDesign** [comment]
Fixed by 08fb2a43d93ab6036637dc5d5efd9c7b6fe2e2d7
