### ISSUE TITLE
raspi-config assumes configuration files are in /boot

### ISSUE THREAD

**Issue by Monofin** [RPi-Distro/raspi-config#118]
Ubuntu aarch64 places the Pi's firmware and config files in /boot/firmware by default, and raspi-config will fail as a result when trying to update the configuration or overlays.

**Comment by XECDesign** [comment]
We don't support third party distros

**Comment by Monofin** [comment]
(Assign this to me if you like, I have a patch that parameterises and checks for Ubuntu?)

**Comment by XECDesign** [comment]
Are the config files auto-generated? I've seen some setups where that happens, in which case raspi-config changes would be overwritten when they get re-generated.

How much complexity does the patch add?

My concerns is that gentoo, arch and all the others would need to be supported too, so I would rather this sort of patch was applied downstream.

**Comment by Monofin** [comment]
NP. I'll make a few more tests for auto generation, it may be a dpkg thing. Management of that many distro would become a headache, I understand if you don't want to open the floodgates!

**Comment by dl6dbh** [comment]
ich habe ein debian 10 buster 64 bit laufen 
kann ich das tool darauf laufen lassen ?
