### ISSUE TITLE
No network option available inside raspi-config after running apt upgrade

### ISSUE THREAD

**Issue by GChuf** [RPi-Distro/raspi-config#142]
I'm running a minimal raspberry pi OS.
I've noticed the error appeared after running `apt update && upgrade`. I've then tried to run only `apt install raspi-config` on a fresh install and the results were the same.

Running kernel 5.4.72 after upgrade, or 5.4.51 when just upgrading raspi-config on a `Pi 3 Model B rev1.2`.

![rpi_bug](https://user-images.githubusercontent.com/42591821/100378790-15505f00-3014-11eb-8b78-60b0a6a1b63c.png)

**Comment by XECDesign** [comment]
Doesn't seem to be an error, just a re-organised menu.

**Comment by GChuf** [comment]
Where are the network options then @XECDesign ?
And why is number 7 missing?

**Comment by XECDesign** [comment]
Which option are you after?

**Comment by GChuf** [comment]
I was looking for wifi setup in particular. I think I saw some other network options somewhere ...

I was able to connect to wifi by manually editing wpa_supplicant.conf file though.

**Comment by XECDesign** [comment]
That seems to be under System Options now (1>S1)
