### ISSUE TITLE
cannot disable power LED (model 2 rev b)

### ISSUE THREAD

**Issue by davewood** [RPi-Distro/raspi-config#148]
`Raspberry Pi Model B Rev 2`

```
cat /etc/debian_version 
10.7
```

I just installed the newest raspbian on my pi and I am trying to disable the power LED. I think this used to work like 2 year ago.

If I select the option in raspi-config I get
`The LED behaviour cannot be changed on this model of Raspberry Pi`
 followed by `There was an error running option S8 Power LED`

raspi-config checks `/sys/class/leds/led0/trigger`
https://github.com/RPi-Distro/raspi-config/blob/master/raspi-config#L1134
 and it seems on my model the path is different:

```
pi@raspberrypi:~ $ cat /sys/class/leds/default-on/trigger 
none rc-feedback kbd-scrolllock kbd-numlock kbd-capslock kbd-kanalock kbd-shiftlock kbd-altgrlock kbd-ctrllock kbd-altlock kbd-shiftllock kbd-shiftrlock kbd-ctrlllock kbd-ctrlrlock timer oneshot heartbeat backlight gpio cpu cpu0 [default-on] input panic actpwr mmc0 rfkill-any rfkill-none phy0rx phy0tx phy0assoc phy0radio rfkill0
```

**Comment by lurch** [comment]
> The LED behaviour cannot be changed on this model of Raspberry Pi

That's correct. As it says at https://gpiozero.readthedocs.io/en/stable/recipes_advanced.html#controlling-the-pi-s-own-leds 
"On the original Pi 1 (model A or B), the activity LED can be controlled with GPIO16 (after disabling its trigger as above) but the power LED is hard-wired on."
