### ISSUE TITLE
Missing the "GL (Full KMS)" option

### ISSUE THREAD

**Issue by Roburetto** [RPi-Distro/raspi-config#152]
Per the documentation(*) a "GL (Full KMS)" item ought to exist under "advanced" options. Still, I only see "GL (Fake KMS)" and "Legacy". How come?

(*) https://www.raspberrypi.org/documentation/configuration/raspi-config.md

I am using a Pi4 with kernel 5.10 from apt in case that matters.

**Comment by spl237** [comment]
Full KMS is not available on Pi 4 platforms at present.
