### ISSUE TITLE
init_resize.sh, whiptail and sleep 5

### ISSUE THREAD

**Issue by dilyanpalauzov** [RPi-Distro/raspi-config#153]
The file usr/lib/raspi-config/init_resize.sh ends with:
```bash
if ! check_commands; then
  reboot_pi
fi

if main; then
  whiptail --infobox "Resized root filesystem. Rebooting in 5 seconds..." 20 60
  sleep 5
else
  sleep 5
  whiptail --msgbox "Could not expand filesystem, please try raspi-config or rc_gui.\n${FAIL_REASON}" 20 60
fi

reboot_pi
```
so it either displays a message and reboots 5seconds later, or it waits 5 seconds, displays a message and reboots immediately.

Whit is the point to have sleep BEFORE whiptail?

**Comment by XECDesign** [comment]
Definitely looks like that was not the intended behaviour. Many thanks!
