### ISSUE TITLE
bug: eeprom does not apply when restart manually

### ISSUE THREAD

**Issue by jayjupdhig** [RPi-Distro/raspi-config#157]
1. start raspi-config
2. chose "lastest" version
3. Say "no" if you will be asked for a soft reboot
4. enter init 0 to shutdown
5. remove drive (so you see the screen with eeprom version)
6. you will still see older (default) version

-> BUG

**Comment by jayjupdhig** [comment]
no anwser??

**Comment by XECDesign** [comment]
When you flash the eeprom, you write files to the sd card which flash it on next boot. If you're taking out the device with those files, then that won't happen. Sounds like you're describing exactly what you'd expect to see.

**Comment by jayjupdhig** [comment]
ok...
