### ISSUE TITLE
FAKE KMS option removed ?

### ISSUE THREAD

**Issue by rnayabed** [RPi-Distro/raspi-config#171]
Newest bullseye release no longer shows FAKE KMS as an option. It is far more stable and usable than the FULL KMS driver that is being shipped By default.

**Comment by XECDesign** [comment]
Right, the focus is on improving the full KMS drivers. You can still use fake KMS by editing config.txt.

I believe the change is intentional.

**Comment by rnayabed** [comment]
> Right, the focus is on improving the full KMS drivers. You can still use fake KMS by editing config.txt.
> 
> I believe the change is intentional.

Instead of removing it from settings you should have at least first marked it with (Deprecated). A lot of screens are unusable with 3d accel as a result because many people aren't savvy enough to edit config and do it themselves.
