### ISSUE TITLE
[FR] Add option to use zram device for overlay upper

### ISSUE THREAD

**Issue by henryptung** [RPi-Distro/raspi-config#175]
This should be a mostly-drop-in replacement for tmpfs in the overlay script, creating a journalless ext4 partition (mounted with `-o discard`) on top of a zram device instead of the current tmpfs.

**Comment by XECDesign** [comment]
Would you happen to have any comparisons for boot times, CPU and RAM usage while doing things like installing large packages and using the browser?

**Comment by henryptung** [comment]
In retrospect, probably not a great idea. tmpfs already supports swapping, so a zram swap device + normal tmpfs essentially allows for uncompressed "caching" while still leveraging zram as needed (vs. direct zram, which would force compression on all reads/writes).

See https://serverfault.com/a/843816/340187
