### ISSUE TITLE
/sys/firmware/devicetree/base/memreserve contains bull value

### ISSUE THREAD

**Issue by sigg3net** [RPi-Distro/raspi-config#192]
Not sure if this belongs here, but I just noticed this:

```
$ cat /sys/firmware/devicetree/base/memreserve 
>`

```
My immediate reaction was to think about the rasp-config entry for reserving memory for the GPU, but it might not be related. In any case it looks like a bash script went rogue here.

**Comment by timg236** [comment]
It's binary

**Comment by XECDesign** [comment]
Doesn't seem related to `raspi-config`.
