### ISSUE TITLE
Does raspi-config work on Ubuntu?

### ISSUE THREAD

**Issue by akash07k** [RPi-Distro/raspi-config#198]
Does raspi-config works well on Ubuntu?
I've installed Ubuntu 22.04 Server on my Raspberry Pi 4B and I want to use raspi-config.

**Comment by XECDesign** [comment]
The version of raspi-config in this repo is written with only Raspberry Pi OS in mind and would not work well with any other distro. Ubuntu has its own patched version which I can't vouch for.
