### ISSUE TITLE
How can I access a raspi-config submenus directly?

### ISSUE THREAD

**Issue by fedekrum** [RPi-Distro/raspi-config#206]
I am working on a script that needs to access raspi-config at "Interface Options > I2C" directly. Is there a way to do this at the command line ?

Thanks

**Comment by cinderblock** [comment]
Yes. As users discovered [here](https://forums.raspberrypi.com/viewtopic.php?t=21632), it's fully supported, albeit un-documented, afaik. No idea if this is considered stable.

```bash
sudo raspi-config nonint do_i2c 0 # Enable I2C
sudo raspi-config nonint do_i2c 1 # Disable I2C
```

Most settings in `raspi-config` follow this standard of `do_XXXX 0` to enable XXXX.

If you're looking for how this is supported, the important entry lines are:

https://github.com/RPi-Distro/raspi-config/blob/master/raspi-config#L2937-L2939

They take all arguments after `nonint` and just call them directly. So you can call other functions in the bash file directly.

Note, there is no direct way to launch just that submenu, afaik. You could `source` the shell script, set `INTERACTIVE=true`, and then run `do_i2c` to maybe get it to work... But I'm sure that is very unsupported usage.
