### ISSUE TITLE
do_wifi_ssid_passphrase() fails to set scan_ssid on hidden network

### ISSUE THREAD

**Issue by lairdrt** [RPi-Distro/raspi-config#209]
The code for `do_wifi_ssid_passphrase()` is missing a section that deals with setting the `scan_ssid` parameter within `wpa_suppicant`. This causes, for example, the Raspberry Pi Imager program to "fail" when the user sets the **Hidden SSID** option (i.e., the new image, upon boot, does not configure the wlan interface properly, which of course means you cannot connect to the system via WiFi). Adding the following processes the setting correctly:
```
if [ "$HIDDEN" -ne 0 ]; then
  wpa_cli -i "$IFACE" set_network "$ID" scan_ssid 1 2>&1 | grep -q "OK"
  RET=$((RET + $?))
fi
```
This was added after the section that manages the `PASSPHRASE` setting, around line 2477 in current version.

**Comment by XECDesign** [comment]
Many thanks for spotting this and the fix!

Should be fixed in the next image.
