### ISSUE TITLE
Add a OpenGLES functionality warning to the OpenGL page

### ISSUE THREAD

**Issue by TheBubbleWorks** [RPi-Distro/raspi-config#21]
Hi,

Enabling the OpenGL desktop acceleration support stops OpenGLES based apps from working; this is currently the expected behaviour: raspberrypi/firmware#556

As this will effect a number of OpenGL ES based applications and libraries (including the bundled VideoCore examples under /opt/vc) already in the wild, please could you add a warning on the settings page along the lines of:

"WARNING: Enabling this option disables OpenGL ES for both console only and desktop applications."

Thanks.

**Comment by XECDesign** [comment]
The issues should be reported here:
https://github.com/anholt/mesa/issues
We can't possibly list all of them in raspi-config and the 'experimental' part should make it clear that things are expected to break.
