### ISSUE TITLE
Disallow using more than 75% of RAM for GPU

### ISSUE THREAD

**Issue by H3wastooshort** [RPi-Distro/raspi-config#221]
I somehow managed to accidentally configure a gpu_mem value over 6000. Took me quite a while to figure that out.

**Comment by lurch** [comment]
https://www.raspberrypi.com/documentation/computers/legacy_config_txt.html#gpu_mem gives maximum recommended values.

**Comment by XECDesign** [comment]
I'm not seeing an option to change gpu mem in bookworm. The legacy release only gets security updates.
