### ISSUE TITLE
Enabling/disabling VNC for wayland desktop does nothing since wayvnc unit file does not exist

### ISSUE THREAD

**Issue by andrum993** [RPi-Distro/raspi-config#229]
raspi-config was recently updated to use a systemd service to run the wayvnc VNC server, instead of the previous method. Unfortunately when raspi-config attempts to enable or disable wayvnc it now does nothing, since the referenced wayvnc unit file does not exist. I'm guessing that there is an updated wayvnc package in the works, but in the meantime raspi-config's option to enable and disable VNC is non-functional on systems where the desktop is using wayland, which is all Pi 4, Pi 400, CM4 and Pi 5 devices by default (but only on those devices which use the graphical desktop, of course).

Also, raspi-config itself appears to not handle the failure to enable the VNC server properly:
![20231215_16h46m13s_grim-1](https://github.com/RPi-Distro/raspi-config/assets/137400510/2fc38370-4440-4992-bfb7-4a744f8a15e1)

Tested on a Pi 4.

**Comment by andrum993** [comment]
See also https://github.com/raspberrypi/bookworm-feedback/issues/174

**Comment by XECDesign** [comment]
Fixed in 77c6b95d3bea51125a9c523164edc336d0b6c53c
