### ISSUE TITLE
feat: print out config values in nonint mode

### ISSUE THREAD

**Issue by guerda** [RPi-Distro/raspi-config#232]
It's great that `raspi-config` lets you set values in an non-interactive way via `nonint`.

In order to make this even better, it would be great if you also can read out the existing configuration via non-int mode, to backup configuration etc.

It could look like this:

    $ sudo raspi-config nonint do_audio
    0

I don't know if that's possible for all options, but it could be a good start to let you automate the config.

**Comment by XECDesign** [comment]
It's a bit outside of the scope of what raspi-config is meant to be for. The nonint functionality is primarily there for rc_gui, not general use. The interface can and will change without any notice.

There are some get_* functions there already, but again, this isn't something we're claiming to provide support for.

**Comment by guerda** [comment]
OK, I understand that. Maybe that should be put as a warning notice on the documentation page, too.

**Comment by XECDesign** [comment]
Yup, I think that can be done as an issue or a PR [here](https://github.com/raspberrypi/documentation/).
