### ISSUE TITLE
What does this tool do?

### ISSUE THREAD

**Issue by lamyergeier** [RPi-Distro/raspi-config#233]
Hello I am a beginner. Could you please explain what does this tool do? Any pros and cons.

**Comment by XECDesign** [comment]
Github issues are generally for reporting issues, so [the forum](https://forums.raspberrypi.com/) might be a more appropriate place for general questions like this.

But the short version is that it's a tool to configure your raspberry pi without having to manually edit files and run multiple commands yourself.
