### ISSUE TITLE
Support setting config_hdmi_boost

### ISSUE THREAD

**Issue by PanderMusubi** [RPi-Distro/raspi-config#30]
Plesae, support setting config_hdmi_boost (with the proper warning or info such as only use this when HDMI output is not strong enough and use the lowest  level possible).

```
CONFIG_HDMI_BOOST

Configures the signal strength of the HDMI interface; the default value is 0 and the maximum is 7. Try 4 if you have interference issues with HDMI.
```

from https://www.raspberrypi.org/documentation/configuration/config-txt.md

**Comment by Romeo-Golf** [comment]
I guess this could be useful in some use cases....

**Comment by PanderMusubi** [comment]
Especially when using a HDMI splitter cable.

**Comment by XECDesign** [comment]
This is an option that should not be touched by the average user and can have negative consequences. It's outside of the scope of what raspi-config is for.
