### ISSUE TITLE
GPIO server - autostart

### ISSUE THREAD

**Issue by britannia2** [RPi-Distro/raspi-config#35]
The GPIO Server setting should be persistant.

Could you add 'systemctl enable pigpiod.service' in case of

1. ‘Advanced Options’
2. ‘GPIO Server’
3. ‘Would you like the GPIO server to be accessible over the network?’ = ‘Yes’

so that pigpiod is also started after a reboot.

**Comment by XECDesign** [comment]
Since gpiod has a very high CPU usage while doing nothing, we believe it should be started by the user as needed.
