### ISSUE TITLE
Overclocking Option not working for Rasperry Pi Zero

### ISSUE THREAD

**Issue by BouncingBit** [RPi-Distro/raspi-config#36]
I've tried to change the Overclock option when using my new Rasperry Pi Zero. I know, that the CPU by itself is already clocked at 1000 MhZ, thus I guess this option doesn't make sense for the Pi Zero anyway, right? This isn't a bug per se, but should this option be disabled for the Pi Zero?

**Comment by XECDesign** [comment]
Correct, the options are only meant for pi 1 and pi 2.

**Comment by BouncingBit** [comment]
Okay, shall I close this issue then, or is there a possiblity to disable the option for the Rasperry Pi Zero programatically?

**Comment by XECDesign** [comment]
What do you mean by that? The option should already say that the board can't be overclocked. Are you seeing something different?

**Comment by BouncingBit** [comment]
Sorry. You're right. There indeed is an appropriate message "This Pi cannot be overclocked" and then "There was an error running option 8 Overclock". Hm... I thought I saw some screen where the clocking speed was displayed as 700 Mhz... strange...
