### ISSUE TITLE
X11 error reported when configuring Force Audio > HDMI

### ISSUE THREAD

**Issue by jsavage** [RPi-Distro/raspi-config#37]
While connected using SSH  (ssh -Y -p 8205 pi@<IP>) to a headless pi running latest Jessie
```
$ uname -a
Linux raspberrypi6 4.4.24-v7+ #1 SMP Mon Oct 10 21:48:58 UTC 2016 armv7l GNU/Linux

```
I decided to force audio > HDMI using raspi-config.  Exited raspi-config normally but then noticed the following had been reported to REPL.
```
X11 connection rejected because of wrong authentication.
xcb_connection_has_error() returned true
numid=3,iface=MIXER,name='Mic Capture Volume'
  ; type=INTEGER,access=rw---R--,values=1,min=0,max=7936,step=0
  : values=2
  | dBminmax-min=0.00dB,max=31.00dB
```
This looks like an error was encountered with X11.  To check this I ran xclock which displayed on my pc as expected. At the very least this error message could do with clarification.
I have not yet been able to confirm whether audio is forced or not but will update this if I find out more.

**Comment by XECDesign** [comment]
All that it's doing is calling amixer, which has not been modified by us. X11 forwarding doesn't work when using sudo (by default). It looks like despite the messages, it's still doing the right thing, so it doesn't look like this is a real issue.

Or is the change actually not having any affect?
