### ISSUE TITLE
SSH Option Missing

### ISSUE THREAD

**Issue by ev3y2** [RPi-Distro/raspi-config#48]
the SSH option (along with some others) is missing from the Advanced Options sub-menu

**Comment by XECDesign** [comment]
I believe that's because it's in the interfacing options menu instead.

**Comment by ev3y2** [comment]
Ah, you're right, thank you.
I'm not aware of the details of this change, but perhaps the documentation [here](https://github.com/raspberrypi/documentation/blob/master/remote-access/ssh/README.md) should be updated accordingly?

**Comment by XECDesign** [comment]
Sent a PR https://github.com/raspberrypi/documentation/pull/543
