### ISSUE TITLE
Command line options

### ISSUE THREAD

**Issue by walchko** [RPi-Distro/raspi-config#55]
Could command line options be added so this could be run from a script? At times I setup a bunch of these and it gets tedious going through all of the menus. Or is that not possible (or maybe better words would be "too difficult")?

**Comment by XECDesign** [comment]
That's already an option. https://github.com/raspberrypi-ui/rc_gui/blob/master/src/rc_gui.c#L23

**Comment by walchko** [comment]
wow, thanks! I googled around and never found this ... maybe I didn't try hard enough or pick the right keywords. I suggest this gets added to some documentation somewhere (maybe a readme.md in the repo). Thanks again!

**Comment by XECDesign** [comment]
Pull requests for documentation are always welcome. raspi-config documentation has been in need of an update for a while, I think.

**Comment by walchko** [comment]
Sure, give me some time (I have to play with what you showed me) and I will do something.
