### ISSUE TITLE
disable VNC returns incorrect message

### ISSUE THREAD

**Issue by harryd16** [RPi-Distro/raspi-config#57]
Rasbian Version: 2017-04-10
Disabling VNC in raspi-config tool returns the message: "The VNC server is enabled"

**Comment by XECDesign** [comment]
Just tried this. What are the steps to reproduce it starting with the latest clean desktop image?

**Comment by harryd16** [comment]
Placed ssh file to enable headless pi operation, might have created new user, ran raspi-config and went through each step.

**Comment by XECDesign** [comment]
Worked as expected for me.
