### ISSUE TITLE
VNC / SSH : move to Networking Menu

### ISSUE THREAD

**Issue by bsimmo** [RPi-Distro/raspi-config#71]
Currently _SSH and VNC_ are under _Interfaces_, 
To me they are not interfaces like the others in the menu. (all physical interfaces)
They would be better under _NETWORKING_ as that is where they are used and so one would logically look.

Unfortunately I can see a lot of documentation consequences of moving them.

**Comment by spl237** [comment]
They are in the Interfaces tab in the GUI application (which doesn't have a networking tab), and I try to keep raspi-config in line with that where possible. So I think they should stay where they are.
