### ISSUE TITLE
system is booting up see pam_nologin

### ISSUE THREAD

**Issue by mrl98** [RPi-Distro/raspi-config#73]
I'm following Ira Finch's Raspberry Pi VPN server guide.

I have set SSH on and wait for network on boot.

Even though I have a working network and the network lights are lit up on the pi, I get the message "system is booting up see pam_nologin"

I have checked using another PC that /run/nologon does not exist, so something else must be preventing me from logging in.

Any idea what might be causing it and how to get back into my pi?

Best Regards
Martin

**Comment by XECDesign** [comment]
I would recommend asking the author of the guide you're following or on the raspberry pi forum.
