### ISSUE TITLE
typo in VNC-Setting (P3)

### ISSUE THREAD

**Issue by ftg5z** [RPi-Distro/raspi-config#74]
if I set the option to "no" it results in message  <pre>"The VNC Server is enabled"</pre> or <pre>"The VNC Server is                   "</pre>
But apt is not executed if I click on "no", so it's not a technical problem.

Terminal says:
Unit vncserver-x11-serviced.service could not be found.
Failed to disable unit: No such file or directory

I'm using latest raspbian image (2017-11-29-raspbian-stretch-lite.img)

**Comment by patricktokeeffe** [comment]
Confirming present on clean Raspbian Lite Nov 29, 2017 install. No harm, no foul (tho prob does confuse some users). 

xref: #57, #65

**Comment by shatteredsword** [comment]
raspbian lite isn't running an x server, so vnc won't work anyway. it seems like the correct way to fix this issue would take a ton of work as it would require checking to see if the x server is running correctly etc. and then just remove the menu option if it's not.
