### ISSUE TITLE
Selecting Advanced Options ---> Resolution results in returning to main menu after new display driver install.

### ISSUE THREAD

**Issue by jbeyer16** [RPi-Distro/raspi-config#79]
I just installed a driver for an external mini display (UCTRONICS 3.5" HDMI Touch Screen) for a Rpi. Using  the Raspberry Pi Configuration GUI, I can selection the resolution installed by the driver (DMT mode 87 480x320 59Hz 15:9) along with all the typical ones set up by the Pi. However, when using the raspi-config tool at the command line, after navigating from Advanced Options to Resolution and hitting Enter on Resolution, the raspi-config tool exits, flashes the command line screen quick, then re-appears on the main screen. This makes it impossible to change resolution using raspi-config. I don't see any error messages or text to point me as to what may be going wrong. I'm thinking the addition of the new driver / resolution setting might be causing it problems somehow, but I really don't know.

**Comment by XECDesign** [comment]
I think you'd be better off contacting them. If you're referring to this https://github.com/UCTRONICS/UCTRONICS_LCD35_RPI, it's not something we support.

**Comment by jbeyer16** [comment]
Sounds good. Thanks.
