### ISSUE TITLE
Suggestion - Add an option to enable/disable wifi and bluetooth

### ISSUE THREAD

**Issue by xMateMCPE** [RPi-Distro/raspi-config#83]
I know the system tray has an option to disable these, but it is not available in CLI mode

**Comment by XECDesign** [comment]
I think it's best to keep raspi-config focused on tasks commonly required by beginners, at least as much as possible. It seems a little unnecessary to wrap around rfkill like this.

**Comment by xMateMCPE** [comment]
It would probably be useful for beginners, as the Pi probably uses less power when it has Wifi and Bluetooth disabled.
