### ISSUE TITLE
Enabling ssh should ensure host keys exists

### ISSUE THREAD

**Issue by maxnet** [RPi-Distro/raspi-config#85]
It would be nice if raspi-config called `ssh-keygen -A` to ensure host keys exists before enabling SSH.

The hackery that generates them on first boot does not work on setups in which the root file system is normally read-only.

https://github.com/raspberrypi/piserver/issues/34

**Comment by XECDesign** [comment]
Seems to be fixed in https://github.com/RPi-Distro/raspi-config/commit/56d42647833ab7458de900df68a76fddd42709eb
