### ISSUE TITLE
Request: add option to switch ip between dhcp and static

### ISSUE THREAD

**Issue by arkid** [RPi-Distro/raspi-config#87]
Not sure if this is the right place to suggest but I was really surprised this doesn't seem to be part of the config options available in the program.   

Keep up the good work, its a really useful utility!

**Comment by XECDesign** [comment]
In the past, this request was denied because it was considered out of scope of what raspi-config is for. The argument being that it's rare for beginners to need to set up a static IP and raspi-config is a tool to make things easy for beginners. I don't personally have strong feelings either way.

**Comment by arkid** [comment]
Hmmm ok,... I'd argue that there are far more obscure settings already
within the tool... .    Agreed lots of people don't need to alter the IP
but if you are customising the pi its something very common you may want to
do.

Thanks for the msg

**Comment by XECDesign** [comment]
It has been almost a year, so I don't think this is likely to be addressed.
