### ISSUE TITLE
Auto-Login to console - incorrect TERM settings

### ISSUE THREAD

**Issue by cmitu** [RPi-Distro/raspi-config#88]
In https://github.com/RPi-Distro/raspi-config/commit/d33487cbeac581d2ce91d8372f5feb1e2b5b7e3a#diff-abf7d6e1d74604f159aeaaf38a3f3b3aR962 (when setting auto-login to console), the `TERM` option passed to `agetty` are taken from the current user's session - the one that runs `raspi-config`. This can produce incorrect results for the console auto-login session if `raspi-config` is executed remotely and the `TERM` is set to something like `xterm-256color`.
This produces an autologin.conf containing
```
ExecStart=-/sbin/agetty --autologin pi --noclear %I xterm-256color
```
instead of
```
ExecStart=-/sbin/agetty --autologin pi --noclear %I $TERM
```

The console session (via auto-login) should have `TERM=linux`.  I think `$TERM` should be escaped to `\$TERM` to avoid the variable substitution.

**Comment by dandjo** [comment]
Confirming. Replacing `xterm-256color` with `$TERM` in `/etc/systemd/system/getty@tty1.service.d/autologin.conf` solved the problem with strange dialog characters.
