### ISSUE TITLE
why cannot expand File System?

### ISSUE THREAD

**Issue by icefrog-su** [RPi-Distro/raspi-config#98]
![image](https://user-images.githubusercontent.com/35363760/66712836-5ae0a700-edd5-11e9-9ced-1ea943dd69e4.png)

There is no option to extend the file system. Could you tell me the reason?
raspberry pi 3b+ and raspberry 4 4G (centos 7)

**Comment by XECDesign** [comment]
raspi-config is a tool for Raspbian. Since CentOS is a completely different distro, it would fail this check here:

https://github.com/RPi-Distro/raspi-config/blob/master/raspi-config#L11

**Comment by icefrog-su** [comment]
Thank you for your answer, based on your answer I also found another solution!
